### ISSUE TITLE
[Tracking] Needed Updates

### ISSUE THREAD

**Issue by Fancy2209** [awayjs/docs#1]
I am looking into doing these.
- [ ] - Add AwayFL since it kinda replaced AwayJS/Player
- [ ] - Update AwayJS Versions used
- [ ] - Update to Latest TypeDoc
- [ ] - Update Theme from Handlebars to React since that's what TypeDoc uses now
